# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: InuYasha's Blog
subtitle: 博客
description: IT
keywords: IT,Java，HTML,JavaScript,CSS,Shell
author: myth
language:
    - zh-CN
    - en
    - zh-HK
    - zh-TW
timezone: Asia/Shanghai
favicon: /favicon.ico
avatar: /favicon.ico


# Directory
source_dir: source
# 发布路径
public_dir: target
# 本地测试1
#public_dir: D:\JavaProject\blog
# 本地测试2
#public_dir: D:\apache-tomcat-8.5.42\webapps\ROOT\blog
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false # Transform title into titlecase
external_link: false # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
    enable: true
    line_number: true
    auto_detect: false
    tab_replace: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
    path: ''
    per_page: 10
    order_by: -date

# Category & Tag
default_category: IT
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: material-x

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://inusha.cn/blog
#root: /blog
# 部署到GitHub
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
# Deployment
## Docs: https://hexo.io/docs/deployment.html
# ssh 方式
#deploy:
#    type: sftp
#    host: inusha.cn
#    port: 22
#    user: myth
#    privateKey: C:\Users\111\.ssh\id_rsa
#    remotePath: /home/myth/soft/apache-tomcat-8.5.43/webapps/ROOT/blog
# git 方式
deploy:
    type: git
    repo: git@github.com:imythu/imythu.github.io.git
    branch: master

# rss
feed:
    type: atom
    path: /blog/atom.xml
    limit: 25
    hub:
    content:
    content_limit:
    content_limit_delim: ' '